[package]
name = "arbitrum-parity"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde = { workspace = true }
serde_json = "1.0"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
